// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qigzljnybrkyznckfown.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpZ3psam55YnJreXpuY2tmb3duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMTY4MjgsImV4cCI6MjA3Mjc5MjgyOH0.v2jaY61c3kQdqThlYrBzo7n4BZYepMmDoBJYkqZv_bE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});